# Generated by Django 5.1.4 on 2024-12-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('individual', models.BooleanField(default=True, verbose_name='Individual')),
                ('active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='ESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'ESP32',
                'verbose_name_plural': 'ESP32',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Nivel')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('begin_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha & Hora de Inicio')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha & Hora de Fiin')),
                ('active', models.BooleanField(default=False, verbose_name='Activo')),
                ('sequence', models.CharField(blank=True, max_length=300, null=True, verbose_name='Secuencia')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_registration', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('good_points', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Aciertos')),
                ('bad_points', models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Errores')),
                ('avg_time_react', models.FloatField(blank=True, default=0, null=True, verbose_name='Tiempo promedio de reacción')),
                ('esp32', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.esp32', verbose_name='Placa')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game', verbose_name='Partida')),
            ],
            options={
                'verbose_name': 'Partida de usuario',
                'verbose_name_plural': 'Partidas de usuario',
            },
        ),
    ]
