# Generated by Django 5.1.4 on 2024-12-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_esp32_user_alter_game_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='sequence',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Secuencia'),
        ),
    ]
