# Generated by Django 5.1.4 on 2024-12-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_game_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
    ]
