# Generated by Django 5.1.4 on 2024-12-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='total',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
