# Generated by Django 5.1.4 on 2024-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='total',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Total'),
        ),
    ]
