# Generated by Django 5.1.4 on 2024-12-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userregistration_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='react_time_sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Suma tiempo de reacción'),
        ),
    ]
